baseURL = "https://ilvolodellasera.web-lecarpanelle.workers.dev/"
locale = "it-IT"
title = "Il Volo della Sera"
theme = "PaperMod"
[pagination]
  pagerSize = 10

[params]
  author = "Fabio Volo"
  defaultTheme = "dark"
  disableThemeToggle = true

[params.label]
  text = "ilVolodellaSera"
  description = "Archivio e riflessioni dal programma di Radio Deejay"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowToc = true

[params.footer]
  text = "[ilvolodellasera.web@gmail.com](mailto:ilvolodellasera.web@gmail.com)"

[params.homeInfoParams]
  Title = "Il Volo del Mattino"
  Content = "Momenti, storie e spunti esistenziali dal programma di Fabio Volo su Radio Deejay."

[[params.socialIcons]]
  name = "link"
  url = "https://www.deejay.it/programmi/il-volo-del-mattino/"

[menu]
  [[menu.main]]
    name = "Archivio"
    url = "/archivio/"
    weight = 1
  [[menu.main]]
    name = "Galleria"
    url = "/galleria/"
    weight = 2
  [[menu.main]]
    name = "Chi siamo"
    url = "/#titolo"
    weight = 3

[taxonomies]
  tema = "temi"

[outputs]
  home = ["HTML", "RSS", "JSON"]
